---
image: node:7.2

stages:
    - test
    # - deploy

variables:
    # CI_BUILD_REF=<commit_hash>
    # CI_BUILD_REF_NAME=<branch_name>
    PIPELINE: $CI_PROJECT_NAME

before_script:
    - env | sort
    # Enable policy
    - rm /usr/sbin/policy-rc.d
    # mongo
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
    - echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list
    - apt-get update
    - apt-get install -y --no-install-recommends mongodb-org-server
    - service mongod start
    - until curl -qs localhost:27017; do echo Waiting for MongoDB; sleep 1; done
    # python and jq
    - apt-get install -y --no-install-recommends jq python python-dev python-pip python-virtualenv
    - pip install -r requirements.txt
    # Clean up apt
    - rm -rf /var/lib/apt/lists/*
    # Upgrade npm
    - npm install -g npm@3
    # clone and start Habitica
    - git clone https://github.com/HabitRPG/habitica.git ../habitica
    - cd ../habitica && cp config.json.example config.json && npm install && cd -

test:
    stage: test
    variables:
        # CI_DEBUG_TRACE: "true"
        HABITICA: "https://hab.rickkasten.com/api/v3"
    script:
        - tests/30-day.sh
        - tests/am-i-sleeping.sh
        - tests/autoforward-missed-dailys.sh
        - tests/cast-party-spells.sh
        - tests/get-tasks.sh
        - tests/get-user-data.sh
        - tests/habitica-backup.sh
        - tests/party-health-check.sh
        - tests/push-todos-with-duedates-to-top.sh
        - tests/set-global-attribute-training.sh

# deploy:
#     stage: deploy
#     script:
#         - ./deploy.sh
#     only:
#         - master
