---
image: node:4.3.1
# image: node:7.2
services:
    - mongo
    - python

stages:
    - test
    # - deploy

variables:
    # CI_BUILD_REF=<commit_hash>
    # CI_BUILD_REF_NAME=<branch_name>
    PIPELINE: $CI_PROJECT_NAME

before_script:
    - env | sort
    # Enable policy
    - rm /usr/sbin/policy-rc.d
    - npm install -g npm@3
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    - echo 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
    - apt-get update
    - apt-get install -y --no-install-recommends jq mongodb-org-server
    - rm -rf /var/lib/apt/lists/*
    - git clone https://github.com/HabitRPG/habitica.git ../habitica
    - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
    - cd ../habitica && cp config.json.example config.json && npm install && cd -

test:
    stage: test
    variables:
        # CI_DEBUG_TRACE: "true"
        HABITICA: "https://hab.rickkasten.com/api/v3"
    script:
        - pip install -r requirements.txt
        - tests/30-day.sh
        - tests/am-i-sleeping.sh
        - tests/autoforward-missed-dailys.sh
        - tests/cast-party-spells.sh
        - tests/get-tasks.sh
        - tests/get-user-data.sh
        - tests/habitica-backup.sh
        - tests/party-health-check.sh
        - tests/push-todos-with-duedates-to-top.sh
        - tests/set-global-attribute-training.sh

# deploy:
#     stage: deploy
#     script:
#         - ./deploy.sh
#     only:
#         - master
