notifications:
  email: false
language: python
python:
  - "2.6"
  - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests
script:
  - tests/30-day.sh
  - tests/am-i-sleeping.sh
  - tests/autoforward-missed-dailys.sh
  - tests/cast-party-spells.sh
  - tests/get-tasks.sh
  - tests/get-user-data.sh
  - tests/habitica-backup.sh
  - tests/push-todos-with-duedates-to-top.sh
  - tests/set-global-attribute-training.sh
