name: push-todos-with-duedates-to-top

on:
  schedule:
    - cron: '00 10 * * *'  # Runs every day at 10:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip
          pip install -q -r requirements.txt

      - name: Run script
        env:
          USER: ${{ secrets.HAB_API_USER }}
          TOKEN: ${{ secrets.HAB_API_TOKEN }}
        run: python push-todos-with-duedates-to-top.py
